import React,  { Component } from 'react';
import './styles.css';

export const About = () => (
  <div className='about'>
    <h1 className='about-header'>ABOUT ME</h1>
    <p className='about-content'>I am a 24 year old guy from Sweden, born and raised about 50 kilometers outside of Stockholm.</p>
    <p className='about-content'>Through out my life I have always had an inherited curiosity about everything slightly interesting, my cousin and close friend would regularly refer to me as Emilpedia for my ability to almost always know at least a little bit about everything. (I might have just been a bit of a besserwisser, but no matter). I have always had a huge appreciation for film as well and I will dig deeper in to my interests in the interests page.</p>
    <p className='about-content'>My working life have consisted of mostly social work, with people who because of different psychological or physical ailments can not live by themselves. It has been extremely giving work and it really humbles you to see the struggles that these people have to go through on a daily basis. Everyone should probably spend some time of their life around people like this, I believe it would put a lot of things in to perspective for many people.</p>
    <p className='about-content'>The last three years of my career have been devoted to Trade union work, focusing on workplace environment regulations and labor laws. I am proud to say that this work have been in the heart of the Swedish model, something many may have heard of. But it is basically that the actual workers should have power over the current labor climate and that we should never work for less than we actually deserve.</p>
    <p className='about-content'>Politics have always been a huge interest of mine, and the last year it has also been part of my professional life, as I have served on a board of the local town council. The board I served on handles questions about local traffic regulations, water and sewage planning and parks. While this may not be the questions closest to my heart, getting a glimpse in to how politics actually work on the inside have been very interesting to say the least. And it have made me mature in my opinions about politics in general.</p>
    <p className='about-content'>Id be remiss to not mention my love for technology and my current career choices. I, as many of my generation, fell for technology at a very early age. Me and my dad started building our own high-tower computer rigs when I was about 8 years old, the first computer we build for me had the old MS NT 3.1 operating system and I remember the thrill of having my own computer in my room. After that I was hooked, while I still enjoyed my old Playstation, the computer was the center of my attention. When I was around 12 I bought my own first chassi and then every Christmas and birthday I would wish for new parts, first to fill it up and later to replace the dated ones. I would always kinda be one or two steps behind on the specs, but I would do my best to push the computer to handle what ever the latest game at the time was. I was very much a learn by doing kind of guy, and I would have to track down new ways to solve new problems all the time (and sometimes to solve old problems as well) but it was always just for fun. While I had dabbled in to coding on and off, trying out some html and some python through the years I never actually considered it as a career for some reason, it was always just a hobby for me. Until a new friend introduced me to the wonders of programming, now in my mid twenties, and holy moly am I sorry I didn’t figure this out earlier. Now most of my free time go to everything that has to do with programming. While I still game on occasion with my friends most of my time on a computer is spent on either learning more about coding or just making stuff for the fun of it.</p>
    <p className='about-content'>So here I am, 24 almost 25, and ready to kickstart my new career in coding!</p>
  </div>
)